💯  TIL 2022-11-30
escape-code-literacy/python-prac pull request #8
Opened 2022-11-30 15:40 UTC by Choo3476

20221130_공부한 내용
반복문, 조건문 간단하게 복습

2022-12-02 02:15 UTC, Choo3476 commented on week1/prac.py
> +    #     result = result + int(i)
코드 주석 제거

2022-12-02 02:17 UTC, Choo3476 commented on week1/day5/5-3.py
> +symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']
list 형태를 같은 iterable 객체인 str로 변경
일일이 입력하는 것을 개선하기 위해 for 구문을 통해 문자열 생성

2022-12-02 02:17 UTC, Choo3476 commented on programmers/level1/핸드폰번호가리기. py
> +# 전화번호가 문자열 phone_number로 주어졌을 때, 전화번호의 뒷 4자리를 제외한 나머지 숫자를 전부 *으로 가린 문자열을 리턴하는 함수, solution을 완성해주세요.
"-" 형태 존재 시 "*"화 예외 처리

2022-12-02 03:23 UTC, Kimdongui reviewed
전체적으로 폴더 구조가 `week`/`day`로 설정 되어있는데, `year`/`month`/`day-day of week` 포멧으로 바꾸면 어떨까요?
```bash
$ 2022/12/02-Friday
```

2022-12-02 03:23 UTC, Kimdongui commented on week1/prac.py
> +    # TO-DO : 함수 구현하기
이건 왜 이렇게 `-`로 표현하셨나요?

2022-12-02 03:23 UTC, Kimdongui commented on week1/prac.py
> +
```suggestion
# Calculate sum of each digit
```
와 같이 주석을 달아두면 나중에 리뷰 할 때 좋습니다.

2022-12-02 03:23 UTC, Kimdongui commented on week1/prac.py
> +        answer = True
`count` 변수를 사용 하지 않고도 구현 할 수 있습니다. 다시 구현해주세요.

2022-12-02 03:23 UTC, Kimdongui commented on programmers/level1/핸드폰번호가리기.py
> +        if i>=(len(phone_number)-4):
if 문을 활용하지 않고 처음부터 4칸을 빼면 어떨까요?

2022-12-02 03:25 UTC, Kimdongui commented on week1/day6/6-2.py
> +# 이 경우 특정 위치에서 무한 루프에 빠질 수 있다. 추후 해당 부분에 대해 디버깅을 진행할 예정
이건 뭔가요?

2022-12-02 03:35 UTC, Choo3476 commented
> 전체적으로 폴더 구조가 `week`/`day`로 설정 되어있는데, `year`/`month`/`day-day of week` 포멧으로 바꾸면 어떨까요?
> 
> ```shell
> $ 2022/12/02-Friday
> ```

아....그것도 좋은데 순공일을 표시하기 위해 day로 하긴 했읍니다
그날 그날 날짜로 생성하면 아주 텀이 보기 좋지 않아질 수 있어서요 ㅎㅎ ^^;;

2022-12-02 03:37 UTC, Choo3476 commented on week1/prac.py
> +
감사합니다

2022-12-02 03:37 UTC, Kimdongui commented on week1/prac.py
> +    # TO-DO : 함수 구현하기
그게 원래 포인트인데요

2022-12-02 03:37 UTC, Kimdongui commented on week1/prac.py
> +
감사할게 아니라 빨리 다세요

2022-12-02 03:37 UTC, Choo3476 commented on week1/day6/6-2.py
> +# 이 경우 특정 위치에서 무한 루프에 빠질 수 있다. 추후 해당 부분에 대해 디버깅을 진행할 예정
link를 타고 들어가면 로봇을 해당 스크립트로 움직일 수 있읍니다

2022-12-02 03:38 UTC, Kimdongui commented
> > 전체적으로 폴더 구조가 `week`/`day`로 설정 되어있는데, `year`/`month`/`day-day of week` 포멧으로 바꾸면 어떨까요?
> > ```shell
> > $ 2022/12/02-Friday
> > ```
> 
> 아....그것도 좋은데 순공일을 표시하기 위해 day로 하긴 했읍니다 그날 그날 날짜로 생성하면 아주 텀이 보기 좋지 않아질 수 있어서요 ㅎㅎ ^^;;

@Brandnew-one

2022-12-02 03:51 UTC, Choo3476 commented on week1/prac.py
> +
아 맞다

2022-12-02 03:51 UTC, Choo3476 commented on week1/prac.py
> +    # TO-DO : 함수 구현하기
아하 수정하겠습니다

2022-12-02 03:52 UTC, Choo3476 commented
> > > 전체적으로 폴더 구조가 `week`/`day`로 설정 되어있는데, `year`/`month`/`day-day of week` 포멧으로 바꾸면 어떨까요?
> > > ```shell
> > > $ 2022/12/02-Friday
> > > ```
> > 
> > 
> > 아....그것도 좋은데 순공일을 표시하기 위해 day로 하긴 했읍니다 그날 그날 날짜로 생성하면 아주 텀이 보기 좋지 않아질 수 있어서요 ㅎㅎ ^^;;
> 
> @Brandnew-one

저를 패기 위해 누군가를 소환하시는 걸까요....??

2022-12-02 04:05 UTC, Choo3476 commented on programmers/level1/핸드폰번호가리기.py
> +        if i>=(len(phone_number)-4):
20221130_modified3_히힣 <- 확인 부탁합니다

2022-12-02 10:25 UTC, hunting-choo commented on week1/prac.py
> +    # TO-DO : 함수 구현하기
커밋아이디에 히힣을 넣었다고요

2022-12-02 10:28 UTC, hunting-choo commented on week1/day6/6-2.py
> +# 이 경우 특정 위치에서 무한 루프에 빠질 수 있다. 추후 해당 부분에 대해 디버깅을 진행할 예정
아..예 그렇군요

2022-12-03 04:25 UTC, Brandnew-one requested changes

2022-12-03 04:25 UTC, Brandnew-one commented on 2022/11/day5/5-3.py
> +
정성스럽게 한땀 한땀 쓴것보다 훨씬 좋군요. 근데 아스키 코드를 외우고 다닐 순 없지 않습니까? 더 간단한 방법이 있을것 같은데

2022-12-03 04:25 UTC, Brandnew-one commented on 2022/previous/prac.py
> +
시간복잡도 O(N) 에서 O(sqrt(N)) 으로 줄일 수 있습니다. 수정해주세요

2022-12-03 04:37 UTC, hunting-choo commented on 2022/11/day5/5-3.py
> +
아주 맛있게 달아주고 계시군요

2022-12-03 05:36 UTC, Choo3476 commented on week1/day4/4-3.py
> +'''
강의보고 구현한거임

2022-12-03 05:41 UTC, Choo3476 commented on week1/day5/5-3.py
> +numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
이거 수정했는데 혹시 수정본이 커밋되지 않았나요....??
동긔님이 지적해서 문자열로 생성하여 바꿨읍니다

2022-12-03 14:40 UTC, Choo3476 commented on programmers/level1/하샤드수.py
> +
각 자리수의 합을 다르게 구해본 것을 2개 함수로 더 첨부했습니다.
그 중 하나인 eval 함수는 파이썬에서 사용 시 악의적인 문자열에 취약 및 호출 위치 노출의 이유로 위험하다고 하는데 실제로 사용에 주의해야 하는지 궁금하네요

2022-12-03 14:41 UTC, Choo3476 commented on week1/day5/5-1.py
> +
[20221203_modified] <- 커밋
max 내장함수가 존재하긴 합니다만, 최댓값 구하는 로직을 구현해봤습니다

2022-12-03 14:42 UTC, Choo3476 commented on week1/day5/5-2.py
> +
아 해당 스크립트는 강의를 들으면서 작성한 것으로,
369 게임과 유사하여 주석을 달았는데, 실제로는 3과 5의 배수일 때 특정 문구 및 3과 5의 동시 배수일 때 특정 문구를 출력하도록 한 상황입니다

2022-12-03 14:44 UTC, Choo3476 commented on 2022/11/day5/5-3.py
> +
[20221203_modified] <- 커밋
ord(x) -> 문자열 x를 역으로 아스키 코드로 반환하는 함수로 해당 함수로 원하는 문자열을 아스키 코드로 치환해 범위로 반복문을 실행하게 변경했습니다.

2022-12-03 14:45 UTC, Choo3476 commented on 2022/previous/prac.py
> +
[20221203_modified] <- 커밋
약수의 원리에 의해 중간값(제곱근)까지만 for구문을 돌리면 나머지 약수들은 이전 중간값까지와의 페어이므로 돌릴 필요가 없어지기 때문에 반복문의 범위를 수정했습니다

2022-12-04 12:54 UTC, Brandnew-one approved these changes

2022-12-04 13:05 UTC, Brandnew-one commented on programmers/level1/하샤드수.py
> +
def3에서 사용하는 eval 함수의 시간복잡도가 얼마나 될지는 저도 잘 모르겠읍니다만 제가 생각한 풀이가 2와 유사합니다.
실제 x의 범위가 4Byte Int를 넘어가는 경우에는 기존의 풀이로 각 자리수의 합을 구할 수 없지만, String Type으로 변환해서 각 자리수를 Int로 바꾸면서 더하면 풀이가 가능하고, 코드 길이도 훨씬 줄어들게 됩니다

2022-12-05 00:25 UTC, hunting-choo approved these changes

2022-12-05 00:26 UTC, hunting-choo commented on 2022/11/day5/5-3.py
> +
이부분 지건이 좀 마렵긴한데 앞으로 맞을 나날들을 위해서 이번 PR은 여기까지 하겠습니다

2022-12-05 00:26 UTC, merged